plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
packageExtensions:
  "webpack-config-single-spa@5.3.0":
    dependencies:
      "webpack": "*"
      "@babel/core": "*"
  "eslint-config-react-important-stuff@3.0.0":
    dependencies:
      "eslint": "*"
  "webpack-config-single-spa-ts@4.1.3":
    dependencies:
      "webpack": "*"
